In [1]:
import os
from pathlib import Path
import pandas as pd
import requests

In [14]:
BASE_PATH = Path("/content/trafficpulse_dataset")

DCRNN_PATH = BASE_PATH / "dcrnn"
SENSOR_PATH = BASE_PATH / "sensor_graph"
WEATHER_PATH = BASE_PATH / "weather"
OSM_PATH = BASE_PATH / "osm"


DCRNN_PATH.mkdir(parents=True, exist_ok=True)
SENSOR_PATH.mkdir(parents=True, exist_ok=True)
WEATHER_PATH.mkdir(parents=True, exist_ok=True)
OSM_PATH.mkdir(parents=True, exist_ok=True)


print("Temporary dataset path:", BASE_PATH)

Temporary dataset path: /content/trafficpulse_dataset

In [15]:
!gdown --folder "https://drive.google.com/drive/folders/10FOTa6HXPqX8Pf5WRoRwcFnW9BrNZEIX" -O /content/trafficpulse_dataset/dcrnn

Retrieving folder contents
Processing file 1pAGRfzMx6K9WWsfDcD1NMbIif0T0saFC metr-la.h5
Processing file 1wD-mHlqAb2mtHOe_68fZvDh1LpDegMMq pems-bay.h5
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1pAGRfzMx6K9WWsfDcD1NMbIif0T0saFC
To: /content/trafficpulse_dataset/dcrnn/metr-la.h5
100% 57.0M/57.0M [00:00<00:00, 130MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1wD-mHlqAb2mtHOe_68fZvDh1LpDegMMq
From (redirected): https://drive.google.com/uc?id=1wD-mHlqAb2mtHOe_68fZvDh1LpDegMMq&confirm=t&uuid=a78701c7-baba-4b21-a495-38c94c7ab5e0
To: /content/trafficpulse_dataset/dcrnn/pems-bay.h5
100% 136M/136M [00:01<00:00, 88.2MB/s]
Download completed

In [16]:
for root, dirs, files in os.walk(BASE_PATH):
    for file in files:
        print(Path(root) / file)

/content/trafficpulse_dataset/dcrnn/metr-la.h5
/content/trafficpulse_dataset/dcrnn/pems-bay.h5
/content/trafficpulse_dataset/sensor_graph/graph_sensor_locations.csv

In [17]:
h5_files = list(BASE_PATH.rglob("*.h5"))

print("Found H5 files:")
for file in h5_files:
    print(file)

metr_path = None

for file in h5_files:
    if "metr" in file.name.lower():
        metr_path = file
        break

if metr_path is None:
    raise FileNotFoundError("METR-LA .h5 file not found.")

print("\nUsing METR-LA file:")
print(metr_path)

Found H5 files:
/content/trafficpulse_dataset/dcrnn/metr-la.h5
/content/trafficpulse_dataset/dcrnn/pems-bay.h5

Using METR-LA file:
/content/trafficpulse_dataset/dcrnn/metr-la.h5

In [18]:
traffic_df = pd.read_hdf(metr_path)

print("METR-LA shape:", traffic_df.shape)
traffic_df.head()

METR-LA shape: (34272, 207)

,773869,767541,767542,717447,717446,717445,773062,767620,737529,717816,...,772167,769372,774204,769806,717590,717592,717595,772168,718141,769373
2012-03-01 00:00:00,64.375000,67.625000,67.125000,61.500000,66.875000,68.750000,65.125,67.125,59.625000,62.750000,...,45.625000,65.500,64.500000,66.428571,66.875,59.375000,69.000000,59.250000,69.000000,61.875
2012-03-01 00:05:00,62.666667,68.555556,65.444444,62.444444,64.444444,68.111111,65.000,65.000,57.444444,63.333333,...,50.666667,69.875,66.666667,58.555556,62.000,61.111111,64.444444,55.888889,68.444444,62.875
2012-03-01 00:10:00,64.000000,63.750000,60.000000,59.000000,66.500000,66.250000,64.500,64.250,63.875000,65.375000,...,44.125000,69.000,56.500000,59.250000,68.125,62.500000,65.625000,61.375000,69.857143,62.000
2012-03-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000,0.000000,0.000000,...,0.000000,0.000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000
2012-03-01 00:20:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000,0.000000,0.000000,...,0.000000,0.000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000

In [19]:
import requests
from pathlib import Path
import pandas as pd

BASE_PATH = Path("/content/trafficpulse_dataset")
SENSOR_PATH = BASE_PATH / "sensor_graph"
SENSOR_PATH.mkdir(parents=True, exist_ok=True)

sensor_url = "https://raw.githubusercontent.com/liyaguang/DCRNN/master/data/sensor_graph/graph_sensor_locations.csv"
sensor_file = SENSOR_PATH / "graph_sensor_locations.csv"

response = requests.get(sensor_url)

if response.status_code == 200:
    with open(sensor_file, "wb") as f:
        f.write(response.content)
    print("Sensor location file downloaded successfully.")
    print("Saved at:", sensor_file)
else:
    print("Failed to download sensor file.")
    print("Status code:", response.status_code)

Sensor location file downloaded successfully.
Saved at: /content/trafficpulse_dataset/sensor_graph/graph_sensor_locations.csv

In [20]:
sensor_df = pd.read_csv(sensor_file)

print("Sensor location shape:", sensor_df.shape)
print("Columns:", sensor_df.columns.tolist())

sensor_df.head()

Sensor location shape: (207, 4)
Columns: ['index', 'sensor_id', 'latitude', 'longitude']

   index  sensor_id  latitude  longitude
0      0     773869  34.15497 -118.31829
1      1     767541  34.11621 -118.23799
2      2     767542  34.11641 -118.23819
3      3     717447  34.07248 -118.26772
4      4     717446  34.07142 -118.26572

In [21]:
traffic_sensor_ids = set(map(str, traffic_df.columns.tolist()))

print("Number of traffic sensors:", len(traffic_sensor_ids))

sensor_df.head()

Number of traffic sensors: 207

   index  sensor_id  latitude  longitude
0      0     773869  34.15497 -118.31829
1      1     767541  34.11621 -118.23799
2      2     767542  34.11641 -118.23819
3      3     717447  34.07248 -118.26772
4      4     717446  34.07142 -118.26572

In [22]:
sensor_id_col = sensor_df.columns[0]

location_sensor_ids = set(sensor_df[sensor_id_col].astype(str).tolist())

matched = traffic_sensor_ids.intersection(location_sensor_ids)

print("Traffic sensors:", len(traffic_sensor_ids))
print("Location sensors:", len(location_sensor_ids))
print("Matched sensors:", len(matched))
print("Unmatched traffic sensors:", len(traffic_sensor_ids - location_sensor_ids))

Traffic sensors: 207
Location sensors: 207
Matched sensors: 0
Unmatched traffic sensors: 207

In [23]:
traffic_sensor_ids = set(map(str, traffic_df.columns.tolist()))

best_sensor_col = None
best_match_count = 0

for col in sensor_df.columns:
    current_ids = set(sensor_df[col].astype(str).tolist())
    match_count = len(traffic_sensor_ids.intersection(current_ids))

    if match_count > best_match_count:
        best_match_count = match_count
        best_sensor_col = col

lat_col = None
lon_col = None

for col in sensor_df.columns:
    col_lower = col.lower()
    if "lat" in col_lower:
        lat_col = col
    if "lon" in col_lower or "lng" in col_lower:
        lon_col = col

print("Detected sensor ID column:", best_sensor_col)
print("Matched sensors:", best_match_count)
print("Detected latitude column:", lat_col)
print("Detected longitude column:", lon_col)

sensor_df.head()

Detected sensor ID column: sensor_id
Matched sensors: 207
Detected latitude column: latitude
Detected longitude column: longitude

   index  sensor_id  latitude  longitude
0      0     773869  34.15497 -118.31829
1      1     767541  34.11621 -118.23799
2      2     767542  34.11641 -118.23819
3      3     717447  34.07248 -118.26772
4      4     717446  34.07142 -118.26572

In [24]:
if best_sensor_col is None:
    raise ValueError("Sensor ID column not detected.")

if lat_col is None or lon_col is None:
    raise ValueError("Latitude/longitude columns not detected.")

start_date = traffic_df.index.min().date()
end_date = traffic_df.index.max().date()

center_lat = sensor_df[lat_col].mean()
center_lon = sensor_df[lon_col].mean()

print("Weather start date:", start_date)
print("Weather end date:", end_date)
print("Center latitude:", center_lat)
print("Center longitude:", center_lon)

Weather start date: 2012-03-01
Weather end date: 2012-06-27
Center latitude: 34.13685429951691
Center longitude: -118.32048154589373

In [25]:
weather_url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": center_lat,
    "longitude": center_lon,
    "start_date": str(start_date),
    "end_date": str(end_date),
    "hourly": [
        "temperature_2m",
        "relative_humidity_2m",
        "precipitation",
        "rain",
        "weather_code",
        "cloud_cover",
        "wind_speed_10m",
        "wind_gusts_10m"
    ],
    "timezone": "America/Los_Angeles"
}

response = requests.get(weather_url, params=params)

print("Status code:", response.status_code)

if response.status_code != 200:
    print(response.text)
    raise Exception("Weather data fetch failed.")

weather_json = response.json()

weather_df = pd.DataFrame(weather_json["hourly"])
weather_df["time"] = pd.to_datetime(weather_df["time"])

weather_file = WEATHER_PATH / "la_weather_metr_la_period.csv"
weather_df.to_csv(weather_file, index=False)

print("Weather dataset loaded successfully.")
print("Shape:", weather_df.shape)
print("Saved at:", weather_file)

weather_df.head()

Status code: 200
Weather dataset loaded successfully.
Shape: (2856, 9)
Saved at: /content/trafficpulse_dataset/weather/la_weather_metr_la_period.csv

,time,temperature_2m,relative_humidity_2m,precipitation,rain,weather_code,cloud_cover,wind_speed_10m,wind_gusts_10m
0,2012-03-01 00:00:00,6.8,94,0.0,0.0,0,11,3.6,12.6
1,2012-03-01 01:00:00,6.6,94,0.0,0.0,1,22,4.0,11.2
2,2012-03-01 02:00:00,6.3,95,0.0,0.0,2,70,4.0,11.5
3,2012-03-01 03:00:00,6.5,95,0.0,0.0,2,78,2.2,11.5
4,2012-03-01 04:00:00,6.4,96,0.0,0.0,2,78,1.6,11.2

In [26]:
print("Weather start:", weather_df["time"].min())
print("Weather end:", weather_df["time"].max())
print("Columns:", weather_df.columns.tolist())

weather_df.head()

Weather start: 2012-03-01 00:00:00
Weather end: 2012-06-27 23:00:00
Columns: ['time', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'rain', 'weather_code', 'cloud_cover', 'wind_speed_10m', 'wind_gusts_10m']

,time,temperature_2m,relative_humidity_2m,precipitation,rain,weather_code,cloud_cover,wind_speed_10m,wind_gusts_10m
0,2012-03-01 00:00:00,6.8,94,0.0,0.0,0,11,3.6,12.6
1,2012-03-01 01:00:00,6.6,94,0.0,0.0,1,22,4.0,11.2
2,2012-03-01 02:00:00,6.3,95,0.0,0.0,2,70,4.0,11.5
3,2012-03-01 03:00:00,6.5,95,0.0,0.0,2,78,2.2,11.5
4,2012-03-01 04:00:00,6.4,96,0.0,0.0,2,78,1.6,11.2

In [28]:
import osmnx as ox
from shapely.geometry import box

# Bounding box around all sensors with small buffer
buffer = 0.03

north = sensor_df[lat_col].max() + buffer
south = sensor_df[lat_col].min() - buffer
east = sensor_df[lon_col].max() + buffer
west = sensor_df[lon_col].min() - buffer

print("North:", north)
print("South:", south)
print("East:", east)
print("West:", west)

polygon = box(west, south, east, north)

G = ox.graph_from_polygon(
    polygon,
    network_type="drive",
    simplify=True
)

nodes_gdf, edges_gdf = ox.graph_to_gdfs(G)

print("OSM road network loaded successfully.")
print("Nodes shape:", nodes_gdf.shape)
print("Edges shape:", edges_gdf.shape)

edges_gdf.head()

North: 34.25164
South: 34.01301
East: -118.1529
West: -118.5668
OSM road network loaded successfully.
Nodes shape: (42613, 8)
Edges shape: (117290, 15)

                                                               osmid  \
u      v          key
653688 21300195   0     [907145138, 895315641, 895315642, 398770659]
       1614655105 0    [1376721881, 398770658, 759468526, 759468527]
653689 1711811908 0                                        398771138
       122734100  0                           [404964730, 398771139]
       1711811906 0                                        643327598

                         highway      lanes maxspeed                name  \
u      v          key
653688 21300195   0    secondary          6   35 mph  National Boulevard
       1614655105 0    secondary  [5, 6, 4]   35 mph  National Boulevard
653689 1711811908 0    secondary          5   35 mph  National Boulevard
       122734100  0    secondary     [5, 4]   35 mph  National Boulevard
       1711811906 0     tertiary        NaN      NaN     Military Avenue

                       oneway reversed      length  \
u      v          key
653688 21300195   0     False    False   88.746024
       1614655105 0     False     True  102.260072
653689 1711811908 0     False    False   19.377863
       122734100  0     False     True  109.728974
       1711811906 0     False    False   19.493944

                                                                geometry  \
u      v          key
653688 21300195   0    LINESTRING (-118.42955 34.02702, -118.42948 34...
       1614655105 0    LINESTRING (-118.42955 34.02702, -118.4298 34....
653689 1711811908 0    LINESTRING (-118.42547 34.02864, -118.42538 34...
       122734100  0    LINESTRING (-118.42547 34.02864, -118.42556 34...
       1711811906 0    LINESTRING (-118.42547 34.02864, -118.42554 34...

                      bridge  ref tunnel access width junction
u      v          key
653688 21300195   0      NaN  NaN    NaN    NaN   NaN      NaN
       1614655105 0      NaN  NaN    NaN    NaN   NaN      NaN
653689 1711811908 0      NaN  NaN    NaN    NaN   NaN      NaN
       122734100  0      NaN  NaN    NaN    NaN   NaN      NaN
       1711811906 0      NaN  NaN    NaN    NaN   NaN      NaN

In [41]:
edges_gdf.sample(5)

,,,osmid,highway,lanes,maxspeed,name,oneway,reversed,length,geometry,bridge,ref,tunnel,access,width,junction
u,v,key,,,,,,,,,,,,,,,
123060706,123105284,0,13416422,residential,NaN,NaN,Vinevalley Drive,False,True,77.903666,"LINESTRING (-118.35952 34.22821, -118.35922 34...",NaN,NaN,NaN,NaN,NaN,NaN
317644173,317644519,0,"[519578396, 28897646]",motorway_link,1,NaN,NaN,True,False,533.950692,"LINESTRING (-118.22254 34.03207, -118.22278 34...",yes,NaN,NaN,NaN,NaN,NaN
123191816,123191812,0,13383611,residential,NaN,NaN,Montague Street,False,True,39.261400,"LINESTRING (-118.41898 34.24198, -118.41866 34...",NaN,NaN,NaN,NaN,NaN,NaN
7868023199,122699654,0,634085261,residential,NaN,NaN,Virginia Road,False,False,12.379111,"LINESTRING (-118.33307 34.04341, -118.33313 34...",NaN,NaN,NaN,destination,NaN,NaN
840625783,122916294,0,13337235,residential,NaN,NaN,Hillside Avenue,False,True,59.542866,"LINESTRING (-118.36221 34.10217, -118.36159 34...",NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
graphml_path = OSM_PATH / "la_road_network.graphml"
edges_path = OSM_PATH / "la_road_edges.geojson"
nodes_path = OSM_PATH / "la_road_nodes.geojson"

ox.save_graphml(G, filepath=graphml_path)

edges_gdf.to_file(edges_path, driver="GeoJSON")
nodes_gdf.to_file(nodes_path, driver="GeoJSON")

print("Saved GraphML:", graphml_path)
print("Saved edges GeoJSON:", edges_path)
print("Saved nodes GeoJSON:", nodes_path)

Saved GraphML: /content/trafficpulse_dataset/osm/la_road_network.graphml
Saved edges GeoJSON: /content/trafficpulse_dataset/osm/la_road_edges.geojson
Saved nodes GeoJSON: /content/trafficpulse_dataset/osm/la_road_nodes.geojson

In [33]:
print("DATASET LOADING SUMMARY")
print("-" * 40)

print("1. Traffic dataset")
print("   Shape:", traffic_df.shape)
print("   Start:", traffic_df.index.min())
print("   End:", traffic_df.index.max())

print("\n2. Sensor location dataset")
print("   Shape:", sensor_df.shape)
print("   Sensor ID column:", best_sensor_col)
print("   Latitude column:", lat_col)
print("   Longitude column:", lon_col)
print("   Matched sensors:", best_match_count)

print("\n3. Weather dataset")
print("   Shape:", weather_df.shape)
print("   Start:", weather_df["time"].min())
print("   End:", weather_df["time"].max())

print("\n4. OSM road network")
print("   Nodes:", nodes_gdf.shape)
print("   Edges:", edges_gdf.shape)

DATASET LOADING SUMMARY
----------------------------------------
1. Traffic dataset
   Shape: (34272, 207)
   Start: 2012-03-01 00:00:00
   End: 2012-06-27 23:55:00

2. Sensor location dataset
   Shape: (207, 4)
   Sensor ID column: sensor_id
   Latitude column: latitude
   Longitude column: longitude
   Matched sensors: 207

3. Weather dataset
   Shape: (2856, 9)
   Start: 2012-03-01 00:00:00
   End: 2012-06-27 23:00:00

4. OSM road network
   Nodes: (42613, 8)
   Edges: (117290, 15)

In [35]:
!zip -r /content/trafficpulse_raw_datasets.zip /content/trafficpulse_dataset/

  adding: content/trafficpulse_dataset/ (stored 0%)
  adding: content/trafficpulse_dataset/weather/ (stored 0%)
  adding: content/trafficpulse_dataset/weather/la_weather_metr_la_period.csv (deflated 79%)
  adding: content/trafficpulse_dataset/dcrnn/ (stored 0%)
  adding: content/trafficpulse_dataset/dcrnn/metr-la.h5 (deflated 78%)
  adding: content/trafficpulse_dataset/dcrnn/pems-bay.h5 (deflated 78%)
  adding: content/trafficpulse_dataset/sensor_graph/ (stored 0%)
  adding: content/trafficpulse_dataset/sensor_graph/graph_sensor_locations.csv (deflated 62%)
  adding: content/trafficpulse_dataset/osm/ (stored 0%)
  adding: content/trafficpulse_dataset/osm/la_road_nodes.geojson (deflated 92%)
  adding: content/trafficpulse_dataset/osm/la_road_edges.geojson (deflated 87%)
  adding: content/trafficpulse_dataset/osm/la_road_network.graphml (deflated 85%)

In [36]:
from google.colab import files

files.download("/content/trafficpulse_raw_datasets.zip")